### ISSUE TITLE
ASP core 6 LTS and some views

### ISSUE THREAD

**Issue by fasteddys** [wowbios/FluentMermaid#12]
Hello, this is nice 👍 , can you please share/add some views in ASP MVC core `.NET6 LTS` (2.0 is not longer supported.)

Also, is this exported in JSON format.

thanks

**Comment by wowbios** [comment]
Hi!
Will add examples ASAP
And no, there is no JSON format (see https://github.com/mermaid-js/mermaid/issues/518)

**Comment by fasteddys** [comment]
@wowbios thanks for that response this is amazing!!

Can you share some guidance on how we can store and retrieve from DB, I ask because if its JSON i can store a strongly typed C# object.

I am not sure how to handle the encoding for mermaid, can you please recommend some suggestions.

**Comment by wowbios** [comment]
@fasteddys mermaid-js, as i said, doesn`t support JSON formatted diagram. Mermaid syntax is description in plain/text format. You can store mermaid syntax text inside any DB that supports text values.

UTF-8 should be ok
